if(WIN32)
    set(WEBRTC_PACK_PLATFORM win)
elseif(APPLE)
    set(WEBRTC_PACK_PLATFORM darwin)
else()
    set(WEBRTC_PACK_PLATFORM linux)
endif()

string(TOLOWER ${CMAKE_HOST_SYSTEM_PROCESSOR} WEBRTC_PACK_ARCHITECTURE)

set(WEBRTC_PACK_NAME webrtc-${WEBRTC_PACK_PLATFORM}-${WEBRTC_PACK_ARCHITECTURE}-${WEBRTC_BUILD_TYPE}.zip)
set(WEBRTC_PACK ${CMAKE_INSTALL_PREFIX}/${WEBRTC_PACK_NAME})

add_custom_command(
    OUTPUT ${WEBRTC_PACK}
    COMMAND ${CMAKE_COMMAND} -E tar cf ${WEBRTC_PACK} --format=zip ${WEBRTC_LIB_FOLDER} ${WEBRTC_HEADERS_FOLDER}
    WORKING_DIRECTORY ${CMAKE_INSTALL_PREFIX}
)

add_custom_target(pack DEPENDS ${WEBRTC_PACK})
add_dependencies(pack setup)
